# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- archive
- author

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-75818367-1
favicon: /assets/icons/favicon.ico
favicon16: /assets/icons/favicon-16x16.png
favicon32: /assets/icons/favicon-32x32.png
faviconapple: /assets/icons/apple-touch-icon.png
faviconandroid192: /assets/icons/android-chrome-192x192.png
faviconandroid512: /assets/icons/android-chrome-512x512.png
webmanifest: /assets/icons/site.webmanifest
twitter: prbuddha
google_plus: JyothiprasadBuddha
fb_admins:
fb_app_id:
